version: '3.1'

services:

  main:
    image: jenkins-master
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /home/jenkins/data/:/var/jenkins_home/
    secrets:
      - jenkins-user
      - jenkins-pass

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
